### ISSUE TITLE
有人在Windows和Linux上接过iphone手机吗？可以直接在atxserver2里面展示吗？

### ISSUE THREAD

**Issue by jeniva** [openatx/atxserver2-ios-provider#27]
目前我Windows上接入会提示报错,这个是iproxy命令在Windows上报错还是啥？想问一下有没有成功的案例可以参考呢？
[D 211209 19:09:10 idb:356] exec: tidevice -u "xxxx877a643ec5e986ccfb6ed1d24636d3685c0 iPhone7" wdaproxy -B ATX-WebDriverAgent --port 0
[D 211209 19:09:12 idb:356] exec: ./iproxy.sh 20000 8100 "xxxx877a643ec5e986ccfb6ed1d24636d3685c0 iPhone7"
ERROR:tornado.application:Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x03D1D5D0>>, <Task finished coro=<WDADevice.run_wda_forever() done, defined at D:\Python\atxserver2-ios-provider-master\idb.py:206> exception=OSError(8, '%1 ▒▒▒▒▒▒Ч▒▒ Win32 Ӧ▒ó▒▒▒', None, 193, None)>)
Traceback (most recent call last):
  File "D:\python3.7.8\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
    ret = callback()
  File "D:\python3.7.8\lib\site-packages\tornado\ioloop.py", line 765, in _discard_future_result
    future.result()
  File "D:\Python\atxserver2-ios-provider-master\idb.py", line 215, in run_wda_forever
    ok = await self.run_webdriveragent()
  File "D:\Python\atxserver2-ios-provider-master\idb.py", line 343, in run_webdriveragent
    silent=True)
  File "D:\Python\atxserver2-ios-provider-master\idb.py", line 357, in run_background
    p = subprocess.Popen(*args, **kwargs)
  File "D:\python3.7.8\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "D:\python3.7.8\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 ▒▒▒▒▒▒Ч▒▒ Win32 Ӧ▒ó▒▒▒
[D 211209 19:09:12 heartbeat:88] websocket send: {'udid': 'xxxx877a643ec5e986ccfb6ed1d24636d3685c0 iPhone7', 'provider': None, 'colding': False, 'properties': {'name': '', 'product': 'Unknown', 'brand': 'Apple'}, 'command': 'update', 'platform': 'apple'}

**Comment by jeniva** [comment]
windows上成功了。

**Comment by chenhengjie123** [comment]
@jeniva 所以问题是已经解决了？

如果是，可以补充下解决方案，便于后人遇到类似问题参考？

**Comment by jeniva** [comment]
把源码里一些基于mac的命令改成tidevice的就好了，看哪里跑不通就改成tidevice命令的
