### ISSUE TITLE
运行错误Cannot find module 'mjpeg-consumer'

### ISSUE THREAD

**Issue by haxx12113** [openatx/atxserver2-ios-provider#7]
[D 190710 10:42:24 heartbeat:88] websocket send: {'udid': 'fa22e915edd5932b7dbad053fbab506651a1fead', 'provider': {'wdaUrl': 'http://10.211.55.3:20002'}, 'properties': {'ip': '10.168.1.172', 'version': '12.3.1', 'sdkVersion': '12.2'}, 'command': 'update', 'platform': 'apple'}
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'mjpeg-consumer'
Require stack:
- /Users/virtual/Desktop/atxserver2/atxserver2-ios-provider/wdaproxy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/virtual/Desktop/atxserver2/atxserver2-ios-provider/wdaproxy.js:16:23)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/virtual/Desktop/atxserver2/atxserver2-ios-provider/wdaproxy.js'
  ]
}
[D 190710 10:43:25 idb:261] [fa22e..ad:“hp”的 iPhone-iPhone 7 Plus] is fine

尝试通过npm install mjpeg-consumer 也是无法安装这个模块

**Comment by codeskyblue** [comment]
试试 node8
